_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
activation:
    value: gelu
batch_size:
    value: 32
c_out:
    value: 1
checkpoints:
    value: ./checkpoints/
d_ff:
    value: 2048
d_layers:
    value: 1
d_model:
    value: 512
data:
    value: custom
data_path:
    value: DailyData.csv
dec_in:
    value: 37
dropout:
    value: 0.05
e_layers:
    value: 2
embed:
    value: fixed
enc_in:
    value: 37
factor:
    value: 1
feature_set:
    value:
        - date
        - Bonds_CHN_10Y
        - Bonds_CHN_1Y
        - Bonds_CHN_2Y
        - Bonds_CHN_5Y
        - Bonds_US_10Y
        - Bonds_US_1Y
        - Bonds_US_2Y
        - Bonds_US_3M
        - Com_BrentCrudeOil
        - Com_Gasoline
        - Com_Silver
        - EPU_GEPU_ppp
        - Stocks_CH50
        - Stocks_SHANGHAI
        - Stocks_US500
        - Stocks_USVIX
        - USD_AUD
        - USD_CNY
        - USD_DXY
        - Com_Gold
features:
    value: MS
former_model:
    value:
        - transformer
        - ns_transformer
freq:
    value: b
gpu:
    value: 0
hidden_size:
    value: 256
label_len:
    value: 45
learning_rate:
    value: 0.0001
loss:
    value: mse
lradj:
    value: type1
model:
    value: mlp
n_heads:
    value: 8
num_layers:
    value: 1
num_train:
    value: 0
num_train_original:
    value: 2248
num_valid:
    value: 0
num_valid_original:
    value: 281
num_workers:
    value: 0
output_attention:
    value: false
p_hidden_dims:
    value:
        - 128
        - 128
p_hidden_layers:
    value: 2
patience:
    value: 3
pred_len:
    value: 90
rnn_model:
    value:
        - rnn
        - lstm
        - mlp
root_path:
    value: /Users/choeseoheon/Desktop/Causal-Discovery/input/
seed:
    value: 2021
seq_len:
    value: 90
target:
    value: Com_Gold
test_ratio:
    value: 0.1
train_epochs:
    value: 5
train_ratio:
    value: 0.8
use_amp:
    value: false
use_gpu:
    value: false
use_multi_gpu:
    value: false
wandb_project:
    value: test1
